# traefik-service.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: traefik
spec:
  # Use LoadBalancer for cloud providers (AWS, GCP, Azure)
  # Change to NodePort if you are running locally or on bare-metal
  type: LoadBalancer 
  selector:
    app: traefik
  ports:
    - protocol: TCP
      name: web
      port: 80
      targetPort: web
    - protocol: TCP
      name: websecure
      port: 443
      targetPort: websecure
    # Service for the Traefik Dashboard/API
    - protocol: TCP
      name: dashboard
      port: 8080
      targetPort: dashboard