apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jaeger-route-16686
  namespace: default
spec:
  entryPoints:
    - jaeger
  routes:
    # PathPrefix matches everything better than HostRegexp for IP-based access
    - match: PathPrefix(`/`) 
      kind: Rule
      services:
        - name: jaeger
          port: 16686