apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-route-3000
  namespace: default
spec:
  entryPoints:
    - grafana
  routes:
    # PathPrefix matches everything better than HostRegexp for IP-based access
    - match: PathPrefix(`/`) 
      kind: Rule
      services:
        - name: grafana
          port: 3000